version: '3.8'

services:
  # NestJS 应用服务
  app:
    build:
      context: ../
      dockerfile: server/Dockerfile
    image: webapp-template-server:latest
    container_name: webapp-template-server
    restart: always
    ports:
      - "8793:8793"
    environment:
      NODE_ENV: production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mongo # 加入同一网络

networks:
  mongo:
    external: true # 引用 mongo 网络
